import { createFileRoute, Link } from '@tanstack/react-router'
import { BarChart3, Building2, CalendarDays, LockKeyhole, Mail, Megaphone, MessageSquare, Users } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useI18n } from '@/i18n/I18nProvider'

export const Route = createFileRoute('/md-preview')({ component: MdOwnerPreview })
const statDefs = [['md.preview.candidates', '248', Users], ['md.preview.employers', '36', Building2], ['md.preview.jobs', '57', BarChart3], ['md.preview.applications', '1,284', Mail]] as const
const workspace = [['md.preview.workspace', Building2, 'md.preview.workspaceDesc'], ['md.preview.meetings', CalendarDays, 'md.preview.meetingsDesc'], ['md.preview.messages', MessageSquare, 'md.preview.messagesDesc'], ['md.preview.marketing', Megaphone, 'md.preview.marketingDesc']] as const

function MdOwnerPreview() {
  const { t, locale, setLocale } = useI18n()
  return <main className="min-h-screen bg-muted/30 px-4 py-6 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl">
    <header className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em]">{t('md.preview.badge')}</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{t('md.preview.title')}</h1><p className="mt-2 max-w-2xl text-sm opacity-80">{t('md.preview.disclaimer')}</p></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" onClick={() => setLocale(locale === 'en' ? 'es' : 'en')} aria-label={t('md.preview.language')}>{locale === 'en' ? 'ES' : 'EN'}</Button><Link to="/"><Button variant="outline" size="sm">{t('md.preview.exit')}</Button></Link></div></div></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label={t('md.preview.metrics')}>{statDefs.map(([key, value, Icon]) => <Card key={key}><CardContent className="p-5"><Icon className="size-5 text-primary" aria-hidden="true"/><p className="mt-3 text-3xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{t(key)}</p></CardContent></Card>)}</section>
    <section className="mt-6 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><CardTitle>{t('md.preview.pipeline')}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3">{[['md.preview.leads','18'],['md.preview.active','12'],['md.preview.paying','7']].map(([key,value]) => <div key={key} className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">{t(key)}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><div><div className="mb-2 flex justify-between text-sm"><span>{t('md.preview.conversion')}</span><strong>39%</strong></div><div className="h-3 rounded-full bg-muted"><div className="h-full w-[39%] rounded-full bg-primary"/></div></div></CardContent></Card><Card><CardHeader><CardTitle>{t('md.preview.revenue')}</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">$6,860</p><p className="text-sm text-muted-foreground">{t('md.preview.projected')}</p><div className="mt-5 flex h-20 items-end gap-2">{[32,45,38,57,50,72].map((height, i) => <div key={i} className="flex-1 rounded-t bg-primary/70" style={{height: `${height}%`}}/>)}</div><p className="mt-2 text-xs text-muted-foreground">{t('md.preview.illustrative')}</p></CardContent></Card></section>
    <section className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{workspace.map(([title, Icon, desc]) => <Card key={title}><CardContent className="p-5"><Icon className="size-5 text-primary" aria-hidden="true"/><h2 className="mt-3 font-semibold">{t(title)}</h2><p className="mt-1 text-sm text-muted-foreground">{t(desc)}</p><Button className="mt-4 w-full" variant="outline" disabled><LockKeyhole className="mr-2 size-4"/>{t('md.preview.only')}</Button></CardContent></Card>)}</section><p className="mt-6 text-center text-xs text-muted-foreground">{t('md.preview.footer')}</p>
  </div></main>
}
