import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
export const Route = createFileRoute('/md-preview')({ component: OwnerPreview })
type Journey='candidate'|'employer'|'md'|'admin'
const labels={en:{badge:'DEVELOPMENT OWNER PREVIEW',title:'Synthetic workspace tour',note:'Read-only synthetic data. No credentials, email, Supabase, or private files are used.',switcher:'Choose a journey',candidate:'Candidate',employer:'Employer',md:'Managing Director',admin:'Admin / HQ',local:'Local-only profile adjustment',name:'Display name',saved:'Saved locally in this browser',locked:'Synthetic preview — unavailable in production',language:'Language'},es:{badge:'VISTA PREVIA DE DESARROLLO',title:'Recorrido de espacios sintéticos',note:'Datos sintéticos de solo lectura. No se usan credenciales, correo, Supabase ni archivos privados.',switcher:'Elige un recorrido',candidate:'Candidato',employer:'Empleador',md:'Director/a gerente',admin:'Administrador / HQ',local:'Ajuste de perfil solo local',name:'Nombre visible',saved:'Guardado localmente en este navegador',locked:'Vista sintética — no disponible en producción',language:'Idioma'}} as const
function OwnerPreview(){const [journey,setJourney]=useState<Journey>('md');const [locale,setLocale]=useState<'en'|'es'>('en');const [name,setName]=useState('María Rodríguez');const t=labels[locale];const title:Record<Journey,string>={candidate:t.candidate,employer:t.employer,md:t.md,admin:t.admin};const data:Record<Journey,string[]>= {candidate:locale==='en'?['Candidate dashboard','Recommended roles','Applications']:['Panel del candidato','Vacantes recomendadas','Postulaciones'],employer:locale==='en'?['Employer command center','Open roles','Candidate pipeline']:['Centro del empleador','Vacantes abiertas','Pipeline de candidatos'],md:locale==='en'?['Managing Director workspace','Employer portfolio','Upcoming meetings']:['Espacio del director gerente','Cartera de empleadores','Próximas reuniones'],admin:locale==='en'?['Admin / HQ operations','Platform health','Pending reviews']:['Operaciones Admin / HQ','Salud de la plataforma','Revisiones pendientes']};return <main className="min-h-screen bg-muted/30 p-4 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-2xl border-2 border-dashed border-amber-400 bg-amber-50 p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold tracking-widest">{t.badge}</p><h1 className="mt-2 text-2xl font-bold">{t.title}</h1><p className="mt-2 text-sm">{t.note}</p></div><Button variant="outline" onClick={()=>setLocale(locale==='en'?'es':'en')} aria-label={t.language}>{locale==='en'?'ES':'EN'}</Button></div></header><Card><CardHeader><CardTitle>{t.switcher}</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{(Object.keys(title) as Journey[]).map(k=><Button key={k} variant={journey===k?'default':'outline'} onClick={()=>setJourney(k)} aria-pressed={journey===k}>{title[k]}</Button>)}</CardContent></Card><section aria-live="polite"><h2 className="text-2xl font-bold">{data[journey][0]}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Card><CardContent className="p-5"><p>{data[journey][1]}</p><p className="mt-3 text-3xl font-bold">12</p><small>{t.locked}</small></CardContent></Card><Card><CardContent className="p-5"><p>{data[journey][2]}</p><p className="mt-3 text-3xl font-bold">8</p><small>{t.locked}</small></CardContent></Card></div></section><Card><CardHeader><CardTitle>{t.local}</CardTitle></CardHeader><CardContent><label htmlFor="preview-name">{t.name}</label><Input id="preview-name" value={name} onChange={e=>setName(e.target.value)} className="mt-2 max-w-md"/><p className="mt-2 text-xs">{t.saved}: {name}</p></CardContent></Card></div></main>}
