import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { AuthGate } from '@/components/AuthGate'
import { useAuth, useIsMd } from '@/hooks/useAuth'
import { useProfile } from '@/hooks/useProfile'
import { useAllProfiles } from '@/hooks/useProfile'
import { useAllJobs } from '@/hooks/useJobs'
import { useAllApplications } from '@/hooks/useApplications'
import { useAllCompanies } from '@/hooks/useCompanies'
import { useI18n } from '@/i18n/I18nProvider'
import { listRows } from '@/lib/supabase'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { LayoutDashboard, Megaphone, MessageSquare, Landmark, Users, Briefcase, FileText, Building2, TrendingUp, Printer } from 'lucide-react'
export const Route = createFileRoute('/_app/md/')({ component: MdDashboard })
function MdDashboard() {
 const {t}=useI18n(); const {user}=useAuth(); const {data:profile,isLoading}=useProfile(user?.id); const isMd=useIsMd(); const navigate=useNavigate(); const {data:profiles=[]}=useAllProfiles(); const {data:jobs=[]}=useAllJobs(); const {data:applications=[]}=useAllApplications(); const {data:companies=[]}=useAllCompanies(); const [leadCount,setLeadCount]=useState(0)
 useEffect(()=>{if(!isLoading&&!isMd)navigate({to:'/dashboard',replace:true})},[isLoading,isMd,navigate]); useEffect(()=>{if(isMd)listRows('leads').then(rows=>setLeadCount(rows.length)).catch(()=>setLeadCount(0))},[isMd])
 const nav=[['/md',LayoutDashboard,'md.nav.dashboard'],['/md/marketing',Megaphone,'md.nav.marketing'],['/md/messages',MessageSquare,'md.nav.messages'],['/md/banking',Landmark,'md.nav.banking'],['/md/employers',Users,'md.nav.employers'],['/md/meetings',Users,'md.nav.meetings'],['/md/profile',Users,'md.nav.profile']]; const candidates=profiles.filter(p=>p.role==='candidate').length, employers=profiles.filter(p=>p.role==='employer').length, openJobs=jobs.filter(j=>j.status==='open').length; const activeEmployers=new Set(jobs.filter(j=>j.status==='open').map(j=>j.employerId)).size; const stats=[[Users,candidates,'md.stats.candidates'],[Building2,employers,'md.stats.employers'],[Briefcase,openJobs,'md.stats.jobs'],[FileText,applications.length,'md.stats.applications'],[TrendingUp,leadCount,'md.stats.leads']]
 return <AuthGate fallbackKey="auth.fallback.dashboard"><main className="mx-auto max-w-6xl p-6 print:p-0"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-muted-foreground">{t('md.welcome')}</p><h1 className="text-3xl font-bold">{t('md.title')}</h1></div><Button variant="outline" className="gap-2 print:hidden" onClick={()=>window.print()}><Printer className="size-4"/>{t('md.report.generate')}</Button></div>{profile?.profileStatus==='pending'?<Card className="mt-8 border-amber-500/30"><CardHeader><CardTitle>{t('md.pendingTitle')}</CardTitle></CardHeader><CardContent>{t('md.pendingDesc')}</CardContent></Card>:<><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{stats.map(([Icon,value,key])=><Card key={String(key)}><CardContent className="p-5"><Icon className="size-5 text-primary"/><p className="mt-3 text-2xl font-bold">{String(value)}</p><p className="text-sm text-muted-foreground">{t(String(key))}</p></CardContent></Card>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>{t('md.pipeline.title')}</CardTitle></CardHeader><CardContent><p>{t('md.pipeline.activeJobs')}: <strong>{activeEmployers}</strong></p><p>{t('md.pipeline.openRoles')}: <strong>{openJobs}</strong></p><p>{t('md.pipeline.companies')}: <strong>{companies.length}</strong></p></CardContent></Card><Card><CardHeader><CardTitle>{t('md.workspace.title')}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{nav.map(([to,Icon,key])=><Link key={String(to)} to={to as any} className="rounded-xl border p-4"><Icon className="size-5 text-primary"/><p className="mt-2 text-sm">{t(String(key))}</p></Link>)}</CardContent></Card></div><Card className="mt-6"><CardHeader><CardTitle>{t('md.revenue.title')}</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">${(activeEmployers*2*49).toLocaleString()}</p><p className="text-sm text-muted-foreground">{t('md.revenue.estMRR')} · {t('md.revenue.activeEmployers')}: {activeEmployers}</p></CardContent></Card></>}</main></AuthGate>
}
