import { createFileRoute } from '@tanstack/react-router'
import { useEffect,useState } from 'react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { AuthGate } from '@/components/AuthGate'
import { useIsMd } from '@/hooks/useAuth'
import { createRow,listRows } from '@/lib/supabase'
import { useI18n } from '@/i18n/I18nProvider'
export const Route=createFileRoute('/_app/md/meetings')({component:Meetings})
function Meetings(){const {t}=useI18n();const ok=useIsMd();const [rows,setRows]=useState<any[]>([]);const [employer,setEmployer]=useState('');const [date,setDate]=useState('');const [notes,setNotes]=useState('');const load=()=>listRows<any>('meetings',{orderBy:{meetingDate:'asc'}}).then(setRows).catch(()=>{});useEffect(()=>{if(ok)load()},[ok]);return <AuthGate fallbackKey="auth.fallback.dashboard"><main className="mx-auto max-w-3xl p-6"><h1 className="text-3xl font-bold">{t('md.meetings.title')}</h1><Card className="mt-6"><CardHeader><CardTitle>{t('md.meetings.schedule')}</CardTitle></CardHeader><CardContent className="grid gap-3"><Input placeholder={t('md.meetings.employer')} value={employer} onChange={e=>setEmployer(e.target.value)}/><Input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><Input placeholder={t('md.meetings.notes')} value={notes} onChange={e=>setNotes(e.target.value)}/><Button disabled={!ok||!employer||!date} onClick={async()=>{await createRow('meetings',{employerName:employer,meetingDate:new Date(date).toISOString(),notes,status:'scheduled'});setEmployer('');setDate('');setNotes('');load()}}>{t('md.meetings.save')}</Button></CardContent></Card><Card className="mt-6"><CardHeader><CardTitle>{t('md.meetings.upcoming')}</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(r=><div key={r.id} className="rounded border p-3"><strong>{r.employerName}</strong><span className="ml-3 text-sm text-muted-foreground">{new Date(r.meetingDate).toLocaleString()}</span><p className="text-sm">{r.notes}</p></div>)}{!rows.length&&<p className="text-muted-foreground">{t('md.meetings.empty')}</p>}</CardContent></Card></main></AuthGate>}
