import { createFileRoute } from '@tanstack/react-router'
import { useEffect,useState } from 'react'
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { AuthGate } from '@/components/AuthGate'
import { useAuth,useIsMd } from '@/hooks/useAuth'
import { createRow,listRows,updateRow } from '@/lib/supabase'
import { sendEmail } from '@/lib/emailSender'
import { useI18n } from '@/i18n/I18nProvider'
export const Route=createFileRoute('/_app/md/messages')({component:Messages})
function Messages(){const {t}=useI18n();const {user}=useAuth();const ok=useIsMd();const [tab,setTab]=useState<'inbox'|'compose'>('inbox');const [rows,setRows]=useState<any[]>([]);const [to,setTo]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const load=()=>listRows<any>('messages',{orderBy:{createdAt:'desc'}}).then(setRows).catch(()=>{});useEffect(()=>{if(ok)load()},[ok]);return <AuthGate fallbackKey="auth.fallback.dashboard"><main className="mx-auto max-w-3xl p-6"><h1 className="text-3xl font-bold">{t('md.messages.title')}</h1><div className="mt-6 flex gap-2"><Button variant={tab==='inbox'?'default':'outline'} onClick={()=>setTab('inbox')}>{t('md.messages.inbox')}</Button><Button variant={tab==='compose'?'default':'outline'} onClick={()=>setTab('compose')}>{t('md.messages.compose')}</Button></div>{tab==='inbox'?<Card className="mt-4"><CardHeader><CardTitle>{t('md.messages.all')}</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(r=><div key={r.id} className="rounded border p-3"><div className="flex justify-between"><strong>{r.subject}</strong><span className="text-xs text-muted-foreground">{r.direction}</span></div><p className="text-sm text-muted-foreground">{r.recipientEmail} · {r.status}</p><p className="mt-1 text-sm">{r.body}</p></div>)}{!rows.length&&<p className="text-muted-foreground">{t('md.messages.empty')}</p>}</CardContent></Card>:<Card className="mt-4"><CardHeader><CardTitle>{t('md.messages.compose')}</CardTitle></CardHeader><CardContent className="grid gap-4"><Input placeholder={t('md.messages.email')} value={to} onChange={e=>setTo(e.target.value)}/><Input placeholder={t('md.messages.subject')} value={subject} onChange={e=>setSubject(e.target.value)}/><textarea className="min-h-40 rounded-md border bg-background p-3" placeholder={t('md.messages.body')} value={body} onChange={e=>setBody(e.target.value)}/><Button disabled={!ok||!to||!subject||!body} onClick={async()=>{const saved=await createRow<any>('messages',{senderId:user?.id,recipientEmail:to,subject,body,direction:'outbound',status:'pending',createdAt:new Date().toISOString()});try{await sendEmail({to,subject,html:`<p>${body.replace(/\n/g,'<br/>')}</p>`});await updateRow('messages',saved.id,{status:'sent'})}catch{await updateRow('messages',saved.id,{status:'failed'})}setBody('');setTab('inbox');load()}}>{t('md.messages.send')}</Button></CardContent></Card>}</main></AuthGate>}
