import { createFileRoute } from '@tanstack/react-router'
import { AuthGate } from '@/components/AuthGate'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/hooks/useAuth'
import { useCompany, useUpdateCompany } from '@/hooks/useCompanies'
import { useI18n } from '@/i18n/I18nProvider'
import { Settings2 } from 'lucide-react'
import { useEffect, useState } from 'react'
export const Route = createFileRoute('/_app/employer/settings')({ component: EmployerSettings })
function EmployerSettings(){const{user}=useAuth();const{data:company,isLoading}=useCompany(user?.id);const update=useUpdateCompany();const{t}=useI18n();const[form,setForm]=useState({name:'',location:'',website:'',contactEmail:'',description:''});useEffect(()=>{if(company)setForm({name:company.name||'',location:company.location||'',website:company.website||'',contactEmail:company.contactEmail||'',description:company.description||''})},[company]);const save=async(e:React.FormEvent)=>{e.preventDefault();if(company)await update.mutateAsync({id:company.id,data:form})};return <AuthGate fallbackKey="auth.fallback.employerDashboard" fallbackDescKey="auth.fallback.employerDashboardDesc"><div className="p-6 max-w-3xl mx-auto"><h1 className="font-serif text-2xl font-bold flex items-center gap-2 mb-1"><Settings2 className="size-6 text-primary"/>{t('nav.settings')}</h1><p className="text-muted-foreground mb-6">{t('settings.subtitle')}</p>{isLoading?<div className="h-64 rounded bg-muted animate-pulse"/>:!company?<Card><CardContent className="py-12 text-center text-muted-foreground">{t('settings.noCompany')}</CardContent></Card>:<Card><CardHeader><CardTitle className="text-base">{t('settings.companyTitle')}</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-4"><Input aria-label={t('settings.companyName')} placeholder={t('settings.companyName')} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Input aria-label={t('settings.location')} placeholder={t('settings.location')} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><Input aria-label={t('settings.website')} placeholder={t('settings.website')} value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/><Input aria-label={t('settings.contactEmail')} placeholder={t('settings.contactEmail')} value={form.contactEmail} onChange={e=>setForm({...form,contactEmail:e.target.value})}/><textarea aria-label={t('settings.description')} placeholder={t('settings.description')} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="min-h-28 w-full rounded-md border bg-background p-3 text-sm"/><Button type="submit" disabled={update.isPending}>{t('common.save')}</Button></form></CardContent></Card>}</div></AuthGate>}
