/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MdPreviewRouteImport } from './routes/md-preview'
import { Route as MRouteImport } from './routes/m'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatePreviewRouteImport } from './routes/candidate-preview'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as MSavedRouteImport } from './routes/m/saved'
import { Route as MProfileRouteImport } from './routes/m/profile'
import { Route as MPostRouteImport } from './routes/m/post'
import { Route as MJobsRouteImport } from './routes/m/jobs'
import { Route as MHomeRouteImport } from './routes/m/home'
import { Route as MCompanyRouteImport } from './routes/m/company'
import { Route as MApplicationsRouteImport } from './routes/m/applications'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as CandidateCreateAccountRouteImport } from './routes/candidate.create-account'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMdRouteImport } from './routes/_app/md'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppHqRouteImport } from './routes/_app/hq'
import { Route as AppEmployerRouteImport } from './routes/_app/employer'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCandidateRouteImport } from './routes/_app/candidate'
import { Route as AppMdIndexRouteImport } from './routes/_app/md/index'
import { Route as AppEmployerIndexRouteImport } from './routes/_app/employer/index'
import { Route as AppCandidateIndexRouteImport } from './routes/_app/candidate/index'
import { Route as MJobsIdRouteImport } from './routes/m/jobs.$id'
import { Route as MEditJobIdRouteImport } from './routes/m/edit-job.$id'
import { Route as AppMdProfileRouteImport } from './routes/_app/md/profile'
import { Route as AppMdMessagesRouteImport } from './routes/_app/md/messages'
import { Route as AppMdMeetingsRouteImport } from './routes/_app/md/meetings'
import { Route as AppMdMarketingRouteImport } from './routes/_app/md/marketing'
import { Route as AppMdEmployersRouteImport } from './routes/_app/md/employers'
import { Route as AppMdBankingRouteImport } from './routes/_app/md/banking'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs.$id'
import { Route as AppHqLeadsRouteImport } from './routes/_app/hq/leads'
import { Route as AppEmployerTeamRouteImport } from './routes/_app/employer/team'
import { Route as AppEmployerSettingsRouteImport } from './routes/_app/employer/settings'
import { Route as AppEmployerPostJobRouteImport } from './routes/_app/employer/post-job'
import { Route as AppEmployerOffersRouteImport } from './routes/_app/employer/offers'
import { Route as AppEmployerMessagesRouteImport } from './routes/_app/employer/messages'
import { Route as AppEmployerJobsRouteImport } from './routes/_app/employer/jobs'
import { Route as AppEmployerApplicationsRouteImport } from './routes/_app/employer/applications'
import { Route as AppEmployerAnalyticsRouteImport } from './routes/_app/employer/analytics'
import { Route as AppCandidateSavedRouteImport } from './routes/_app/candidate/saved'
import { Route as AppCandidateApplicationsRouteImport } from './routes/_app/candidate/applications'
import { Route as AppApplyIdRouteImport } from './routes/_app/apply.$id'
import { Route as AppEmployerManageIdRouteImport } from './routes/_app/employer/manage.$id'
import { Route as AppEmployerEditJobIdRouteImport } from './routes/_app/employer/edit-job.$id'
import { Route as AppApplyIdConfirmRouteImport } from './routes/_app/apply.$id.confirm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MdPreviewRoute = MdPreviewRouteImport.update({
  id: '/md-preview',
  path: '/md-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePreviewRoute = CandidatePreviewRouteImport.update({
  id: '/candidate-preview',
  path: '/candidate-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSavedRoute = MSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MRoute,
} as any)
const MProfileRoute = MProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MRoute,
} as any)
const MPostRoute = MPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => MRoute,
} as any)
const MJobsRoute = MJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => MRoute,
} as any)
const MHomeRoute = MHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MRoute,
} as any)
const MCompanyRoute = MCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => MRoute,
} as any)
const MApplicationsRoute = MApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => MRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateCreateAccountRoute = CandidateCreateAccountRouteImport.update({
  id: '/candidate/create-account',
  path: '/candidate/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMdRoute = AppMdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHqRoute = AppHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerRoute = AppEmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateRoute = AppCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => AppRoute,
} as any)
const AppMdIndexRoute = AppMdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMdRoute,
} as any)
const AppEmployerIndexRoute = AppEmployerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppCandidateIndexRoute = AppCandidateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCandidateRoute,
} as any)
const MJobsIdRoute = MJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MJobsRoute,
} as any)
const MEditJobIdRoute = MEditJobIdRouteImport.update({
  id: '/edit-job/$id',
  path: '/edit-job/$id',
  getParentRoute: () => MRoute,
} as any)
const AppMdProfileRoute = AppMdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdMessagesRoute = AppMdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdMeetingsRoute = AppMdMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdMarketingRoute = AppMdMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdEmployersRoute = AppMdEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdBankingRoute = AppMdBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppMdRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppHqLeadsRoute = AppHqLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppHqRoute,
} as any)
const AppEmployerTeamRoute = AppEmployerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerSettingsRoute = AppEmployerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerPostJobRoute = AppEmployerPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerOffersRoute = AppEmployerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerMessagesRoute = AppEmployerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerJobsRoute = AppEmployerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerApplicationsRoute = AppEmployerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerAnalyticsRoute = AppEmployerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppCandidateSavedRoute = AppCandidateSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateApplicationsRoute =
  AppCandidateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AppCandidateRoute,
  } as any)
const AppApplyIdRoute = AppApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerManageIdRoute = AppEmployerManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppEmployerEditJobIdRoute = AppEmployerEditJobIdRouteImport.update({
  id: '/edit-job/$id',
  path: '/edit-job/$id',
  getParentRoute: () => AppEmployerRoute,
} as any)
const AppApplyIdConfirmRoute = AppApplyIdConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AppApplyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/candidate-preview': typeof CandidatePreviewRoute
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/m': typeof MRouteWithChildren
  '/md-preview': typeof MdPreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/candidate': typeof AppCandidateRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/employer': typeof AppEmployerRouteWithChildren
  '/hq': typeof AppHqRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/md': typeof AppMdRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/candidate/create-account': typeof CandidateCreateAccountRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/applications': typeof MApplicationsRoute
  '/m/company': typeof MCompanyRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/m/': typeof MIndexRoute
  '/apply/$id': typeof AppApplyIdRouteWithChildren
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/saved': typeof AppCandidateSavedRoute
  '/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/employer/applications': typeof AppEmployerApplicationsRoute
  '/employer/jobs': typeof AppEmployerJobsRoute
  '/employer/messages': typeof AppEmployerMessagesRoute
  '/employer/offers': typeof AppEmployerOffersRoute
  '/employer/post-job': typeof AppEmployerPostJobRoute
  '/employer/settings': typeof AppEmployerSettingsRoute
  '/employer/team': typeof AppEmployerTeamRoute
  '/hq/leads': typeof AppHqLeadsRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/md/banking': typeof AppMdBankingRoute
  '/md/employers': typeof AppMdEmployersRoute
  '/md/marketing': typeof AppMdMarketingRoute
  '/md/meetings': typeof AppMdMeetingsRoute
  '/md/messages': typeof AppMdMessagesRoute
  '/md/profile': typeof AppMdProfileRoute
  '/m/edit-job/$id': typeof MEditJobIdRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/candidate/': typeof AppCandidateIndexRoute
  '/employer/': typeof AppEmployerIndexRoute
  '/md/': typeof AppMdIndexRoute
  '/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/candidate-preview': typeof CandidatePreviewRoute
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/md-preview': typeof MdPreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hq': typeof AppHqRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/candidate/create-account': typeof CandidateCreateAccountRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/applications': typeof MApplicationsRoute
  '/m/company': typeof MCompanyRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies': typeof CompaniesIndexRoute
  '/m': typeof MIndexRoute
  '/apply/$id': typeof AppApplyIdRouteWithChildren
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/saved': typeof AppCandidateSavedRoute
  '/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/employer/applications': typeof AppEmployerApplicationsRoute
  '/employer/jobs': typeof AppEmployerJobsRoute
  '/employer/messages': typeof AppEmployerMessagesRoute
  '/employer/offers': typeof AppEmployerOffersRoute
  '/employer/post-job': typeof AppEmployerPostJobRoute
  '/employer/settings': typeof AppEmployerSettingsRoute
  '/employer/team': typeof AppEmployerTeamRoute
  '/hq/leads': typeof AppHqLeadsRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/md/banking': typeof AppMdBankingRoute
  '/md/employers': typeof AppMdEmployersRoute
  '/md/marketing': typeof AppMdMarketingRoute
  '/md/meetings': typeof AppMdMeetingsRoute
  '/md/messages': typeof AppMdMessagesRoute
  '/md/profile': typeof AppMdProfileRoute
  '/m/edit-job/$id': typeof MEditJobIdRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/candidate': typeof AppCandidateIndexRoute
  '/employer': typeof AppEmployerIndexRoute
  '/md': typeof AppMdIndexRoute
  '/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/applications': typeof ApplicationsRoute
  '/candidate-preview': typeof CandidatePreviewRoute
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/m': typeof MRouteWithChildren
  '/md-preview': typeof MdPreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/candidate': typeof AppCandidateRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employer': typeof AppEmployerRouteWithChildren
  '/_app/hq': typeof AppHqRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/md': typeof AppMdRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/candidate/create-account': typeof CandidateCreateAccountRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/applications': typeof MApplicationsRoute
  '/m/company': typeof MCompanyRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/m/': typeof MIndexRoute
  '/_app/apply/$id': typeof AppApplyIdRouteWithChildren
  '/_app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/_app/candidate/saved': typeof AppCandidateSavedRoute
  '/_app/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/_app/employer/applications': typeof AppEmployerApplicationsRoute
  '/_app/employer/jobs': typeof AppEmployerJobsRoute
  '/_app/employer/messages': typeof AppEmployerMessagesRoute
  '/_app/employer/offers': typeof AppEmployerOffersRoute
  '/_app/employer/post-job': typeof AppEmployerPostJobRoute
  '/_app/employer/settings': typeof AppEmployerSettingsRoute
  '/_app/employer/team': typeof AppEmployerTeamRoute
  '/_app/hq/leads': typeof AppHqLeadsRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/md/banking': typeof AppMdBankingRoute
  '/_app/md/employers': typeof AppMdEmployersRoute
  '/_app/md/marketing': typeof AppMdMarketingRoute
  '/_app/md/meetings': typeof AppMdMeetingsRoute
  '/_app/md/messages': typeof AppMdMessagesRoute
  '/_app/md/profile': typeof AppMdProfileRoute
  '/m/edit-job/$id': typeof MEditJobIdRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/_app/candidate/': typeof AppCandidateIndexRoute
  '/_app/employer/': typeof AppEmployerIndexRoute
  '/_app/md/': typeof AppMdIndexRoute
  '/_app/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/_app/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/_app/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/candidate-preview'
    | '/contact'
    | '/for-employers'
    | '/m'
    | '/md-preview'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/reset-password'
    | '/terms'
    | '/candidate'
    | '/dashboard'
    | '/employer'
    | '/hq'
    | '/jobs'
    | '/md'
    | '/profile'
    | '/candidate/create-account'
    | '/companies/$id'
    | '/m/applications'
    | '/m/company'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies/'
    | '/m/'
    | '/apply/$id'
    | '/candidate/applications'
    | '/candidate/saved'
    | '/employer/analytics'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/messages'
    | '/employer/offers'
    | '/employer/post-job'
    | '/employer/settings'
    | '/employer/team'
    | '/hq/leads'
    | '/jobs/$id'
    | '/md/banking'
    | '/md/employers'
    | '/md/marketing'
    | '/md/meetings'
    | '/md/messages'
    | '/md/profile'
    | '/m/edit-job/$id'
    | '/m/jobs/$id'
    | '/candidate/'
    | '/employer/'
    | '/md/'
    | '/apply/$id/confirm'
    | '/employer/edit-job/$id'
    | '/employer/manage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/candidate-preview'
    | '/contact'
    | '/for-employers'
    | '/md-preview'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/hq'
    | '/jobs'
    | '/profile'
    | '/candidate/create-account'
    | '/companies/$id'
    | '/m/applications'
    | '/m/company'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies'
    | '/m'
    | '/apply/$id'
    | '/candidate/applications'
    | '/candidate/saved'
    | '/employer/analytics'
    | '/employer/applications'
    | '/employer/jobs'
    | '/employer/messages'
    | '/employer/offers'
    | '/employer/post-job'
    | '/employer/settings'
    | '/employer/team'
    | '/hq/leads'
    | '/jobs/$id'
    | '/md/banking'
    | '/md/employers'
    | '/md/marketing'
    | '/md/meetings'
    | '/md/messages'
    | '/md/profile'
    | '/m/edit-job/$id'
    | '/m/jobs/$id'
    | '/candidate'
    | '/employer'
    | '/md'
    | '/apply/$id/confirm'
    | '/employer/edit-job/$id'
    | '/employer/manage/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/applications'
    | '/candidate-preview'
    | '/contact'
    | '/for-employers'
    | '/m'
    | '/md-preview'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/reset-password'
    | '/terms'
    | '/_app/candidate'
    | '/_app/dashboard'
    | '/_app/employer'
    | '/_app/hq'
    | '/_app/jobs'
    | '/_app/md'
    | '/_app/profile'
    | '/candidate/create-account'
    | '/companies/$id'
    | '/m/applications'
    | '/m/company'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies/'
    | '/m/'
    | '/_app/apply/$id'
    | '/_app/candidate/applications'
    | '/_app/candidate/saved'
    | '/_app/employer/analytics'
    | '/_app/employer/applications'
    | '/_app/employer/jobs'
    | '/_app/employer/messages'
    | '/_app/employer/offers'
    | '/_app/employer/post-job'
    | '/_app/employer/settings'
    | '/_app/employer/team'
    | '/_app/hq/leads'
    | '/_app/jobs/$id'
    | '/_app/md/banking'
    | '/_app/md/employers'
    | '/_app/md/marketing'
    | '/_app/md/meetings'
    | '/_app/md/messages'
    | '/_app/md/profile'
    | '/m/edit-job/$id'
    | '/m/jobs/$id'
    | '/_app/candidate/'
    | '/_app/employer/'
    | '/_app/md/'
    | '/_app/apply/$id/confirm'
    | '/_app/employer/edit-job/$id'
    | '/_app/employer/manage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRoute
  CandidatePreviewRoute: typeof CandidatePreviewRoute
  ContactRoute: typeof ContactRoute
  ForEmployersRoute: typeof ForEmployersRoute
  MRoute: typeof MRouteWithChildren
  MdPreviewRoute: typeof MdPreviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilesRoute: typeof ProfilesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CandidateCreateAccountRoute: typeof CandidateCreateAccountRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/md-preview': {
      id: '/md-preview'
      path: '/md-preview'
      fullPath: '/md-preview'
      preLoaderRoute: typeof MdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-preview': {
      id: '/candidate-preview'
      path: '/candidate-preview'
      fullPath: '/candidate-preview'
      preLoaderRoute: typeof CandidatePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/saved': {
      id: '/m/saved'
      path: '/saved'
      fullPath: '/m/saved'
      preLoaderRoute: typeof MSavedRouteImport
      parentRoute: typeof MRoute
    }
    '/m/profile': {
      id: '/m/profile'
      path: '/profile'
      fullPath: '/m/profile'
      preLoaderRoute: typeof MProfileRouteImport
      parentRoute: typeof MRoute
    }
    '/m/post': {
      id: '/m/post'
      path: '/post'
      fullPath: '/m/post'
      preLoaderRoute: typeof MPostRouteImport
      parentRoute: typeof MRoute
    }
    '/m/jobs': {
      id: '/m/jobs'
      path: '/jobs'
      fullPath: '/m/jobs'
      preLoaderRoute: typeof MJobsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/home': {
      id: '/m/home'
      path: '/home'
      fullPath: '/m/home'
      preLoaderRoute: typeof MHomeRouteImport
      parentRoute: typeof MRoute
    }
    '/m/company': {
      id: '/m/company'
      path: '/company'
      fullPath: '/m/company'
      preLoaderRoute: typeof MCompanyRouteImport
      parentRoute: typeof MRoute
    }
    '/m/applications': {
      id: '/m/applications'
      path: '/applications'
      fullPath: '/m/applications'
      preLoaderRoute: typeof MApplicationsRouteImport
      parentRoute: typeof MRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/create-account': {
      id: '/candidate/create-account'
      path: '/candidate/create-account'
      fullPath: '/candidate/create-account'
      preLoaderRoute: typeof CandidateCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/md': {
      id: '/_app/md'
      path: '/md'
      fullPath: '/md'
      preLoaderRoute: typeof AppMdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hq': {
      id: '/_app/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AppHqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer': {
      id: '/_app/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof AppEmployerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate': {
      id: '/_app/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AppCandidateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/md/': {
      id: '/_app/md/'
      path: '/'
      fullPath: '/md/'
      preLoaderRoute: typeof AppMdIndexRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/employer/': {
      id: '/_app/employer/'
      path: '/'
      fullPath: '/employer/'
      preLoaderRoute: typeof AppEmployerIndexRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/candidate/': {
      id: '/_app/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AppCandidateIndexRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/m/jobs/$id': {
      id: '/m/jobs/$id'
      path: '/$id'
      fullPath: '/m/jobs/$id'
      preLoaderRoute: typeof MJobsIdRouteImport
      parentRoute: typeof MJobsRoute
    }
    '/m/edit-job/$id': {
      id: '/m/edit-job/$id'
      path: '/edit-job/$id'
      fullPath: '/m/edit-job/$id'
      preLoaderRoute: typeof MEditJobIdRouteImport
      parentRoute: typeof MRoute
    }
    '/_app/md/profile': {
      id: '/_app/md/profile'
      path: '/profile'
      fullPath: '/md/profile'
      preLoaderRoute: typeof AppMdProfileRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/messages': {
      id: '/_app/md/messages'
      path: '/messages'
      fullPath: '/md/messages'
      preLoaderRoute: typeof AppMdMessagesRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/meetings': {
      id: '/_app/md/meetings'
      path: '/meetings'
      fullPath: '/md/meetings'
      preLoaderRoute: typeof AppMdMeetingsRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/marketing': {
      id: '/_app/md/marketing'
      path: '/marketing'
      fullPath: '/md/marketing'
      preLoaderRoute: typeof AppMdMarketingRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/employers': {
      id: '/_app/md/employers'
      path: '/employers'
      fullPath: '/md/employers'
      preLoaderRoute: typeof AppMdEmployersRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/banking': {
      id: '/_app/md/banking'
      path: '/banking'
      fullPath: '/md/banking'
      preLoaderRoute: typeof AppMdBankingRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/hq/leads': {
      id: '/_app/hq/leads'
      path: '/leads'
      fullPath: '/hq/leads'
      preLoaderRoute: typeof AppHqLeadsRouteImport
      parentRoute: typeof AppHqRoute
    }
    '/_app/employer/team': {
      id: '/_app/employer/team'
      path: '/team'
      fullPath: '/employer/team'
      preLoaderRoute: typeof AppEmployerTeamRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/settings': {
      id: '/_app/employer/settings'
      path: '/settings'
      fullPath: '/employer/settings'
      preLoaderRoute: typeof AppEmployerSettingsRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/post-job': {
      id: '/_app/employer/post-job'
      path: '/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof AppEmployerPostJobRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/offers': {
      id: '/_app/employer/offers'
      path: '/offers'
      fullPath: '/employer/offers'
      preLoaderRoute: typeof AppEmployerOffersRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/messages': {
      id: '/_app/employer/messages'
      path: '/messages'
      fullPath: '/employer/messages'
      preLoaderRoute: typeof AppEmployerMessagesRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/jobs': {
      id: '/_app/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AppEmployerJobsRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/applications': {
      id: '/_app/employer/applications'
      path: '/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof AppEmployerApplicationsRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/analytics': {
      id: '/_app/employer/analytics'
      path: '/analytics'
      fullPath: '/employer/analytics'
      preLoaderRoute: typeof AppEmployerAnalyticsRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/candidate/saved': {
      id: '/_app/candidate/saved'
      path: '/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof AppCandidateSavedRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/_app/candidate/applications': {
      id: '/_app/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AppCandidateApplicationsRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/_app/apply/$id': {
      id: '/_app/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof AppApplyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/manage/$id': {
      id: '/_app/employer/manage/$id'
      path: '/manage/$id'
      fullPath: '/employer/manage/$id'
      preLoaderRoute: typeof AppEmployerManageIdRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/employer/edit-job/$id': {
      id: '/_app/employer/edit-job/$id'
      path: '/edit-job/$id'
      fullPath: '/employer/edit-job/$id'
      preLoaderRoute: typeof AppEmployerEditJobIdRouteImport
      parentRoute: typeof AppEmployerRoute
    }
    '/_app/apply/$id/confirm': {
      id: '/_app/apply/$id/confirm'
      path: '/confirm'
      fullPath: '/apply/$id/confirm'
      preLoaderRoute: typeof AppApplyIdConfirmRouteImport
      parentRoute: typeof AppApplyIdRoute
    }
  }
}

interface AppCandidateRouteChildren {
  AppCandidateApplicationsRoute: typeof AppCandidateApplicationsRoute
  AppCandidateSavedRoute: typeof AppCandidateSavedRoute
  AppCandidateIndexRoute: typeof AppCandidateIndexRoute
}

const AppCandidateRouteChildren: AppCandidateRouteChildren = {
  AppCandidateApplicationsRoute: AppCandidateApplicationsRoute,
  AppCandidateSavedRoute: AppCandidateSavedRoute,
  AppCandidateIndexRoute: AppCandidateIndexRoute,
}

const AppCandidateRouteWithChildren = AppCandidateRoute._addFileChildren(
  AppCandidateRouteChildren,
)

interface AppEmployerRouteChildren {
  AppEmployerAnalyticsRoute: typeof AppEmployerAnalyticsRoute
  AppEmployerApplicationsRoute: typeof AppEmployerApplicationsRoute
  AppEmployerJobsRoute: typeof AppEmployerJobsRoute
  AppEmployerMessagesRoute: typeof AppEmployerMessagesRoute
  AppEmployerOffersRoute: typeof AppEmployerOffersRoute
  AppEmployerPostJobRoute: typeof AppEmployerPostJobRoute
  AppEmployerSettingsRoute: typeof AppEmployerSettingsRoute
  AppEmployerTeamRoute: typeof AppEmployerTeamRoute
  AppEmployerIndexRoute: typeof AppEmployerIndexRoute
  AppEmployerEditJobIdRoute: typeof AppEmployerEditJobIdRoute
  AppEmployerManageIdRoute: typeof AppEmployerManageIdRoute
}

const AppEmployerRouteChildren: AppEmployerRouteChildren = {
  AppEmployerAnalyticsRoute: AppEmployerAnalyticsRoute,
  AppEmployerApplicationsRoute: AppEmployerApplicationsRoute,
  AppEmployerJobsRoute: AppEmployerJobsRoute,
  AppEmployerMessagesRoute: AppEmployerMessagesRoute,
  AppEmployerOffersRoute: AppEmployerOffersRoute,
  AppEmployerPostJobRoute: AppEmployerPostJobRoute,
  AppEmployerSettingsRoute: AppEmployerSettingsRoute,
  AppEmployerTeamRoute: AppEmployerTeamRoute,
  AppEmployerIndexRoute: AppEmployerIndexRoute,
  AppEmployerEditJobIdRoute: AppEmployerEditJobIdRoute,
  AppEmployerManageIdRoute: AppEmployerManageIdRoute,
}

const AppEmployerRouteWithChildren = AppEmployerRoute._addFileChildren(
  AppEmployerRouteChildren,
)

interface AppHqRouteChildren {
  AppHqLeadsRoute: typeof AppHqLeadsRoute
}

const AppHqRouteChildren: AppHqRouteChildren = {
  AppHqLeadsRoute: AppHqLeadsRoute,
}

const AppHqRouteWithChildren = AppHqRoute._addFileChildren(AppHqRouteChildren)

interface AppJobsRouteChildren {
  AppJobsIdRoute: typeof AppJobsIdRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsIdRoute: AppJobsIdRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppMdRouteChildren {
  AppMdBankingRoute: typeof AppMdBankingRoute
  AppMdEmployersRoute: typeof AppMdEmployersRoute
  AppMdMarketingRoute: typeof AppMdMarketingRoute
  AppMdMeetingsRoute: typeof AppMdMeetingsRoute
  AppMdMessagesRoute: typeof AppMdMessagesRoute
  AppMdProfileRoute: typeof AppMdProfileRoute
  AppMdIndexRoute: typeof AppMdIndexRoute
}

const AppMdRouteChildren: AppMdRouteChildren = {
  AppMdBankingRoute: AppMdBankingRoute,
  AppMdEmployersRoute: AppMdEmployersRoute,
  AppMdMarketingRoute: AppMdMarketingRoute,
  AppMdMeetingsRoute: AppMdMeetingsRoute,
  AppMdMessagesRoute: AppMdMessagesRoute,
  AppMdProfileRoute: AppMdProfileRoute,
  AppMdIndexRoute: AppMdIndexRoute,
}

const AppMdRouteWithChildren = AppMdRoute._addFileChildren(AppMdRouteChildren)

interface AppApplyIdRouteChildren {
  AppApplyIdConfirmRoute: typeof AppApplyIdConfirmRoute
}

const AppApplyIdRouteChildren: AppApplyIdRouteChildren = {
  AppApplyIdConfirmRoute: AppApplyIdConfirmRoute,
}

const AppApplyIdRouteWithChildren = AppApplyIdRoute._addFileChildren(
  AppApplyIdRouteChildren,
)

interface AppRouteChildren {
  AppCandidateRoute: typeof AppCandidateRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployerRoute: typeof AppEmployerRouteWithChildren
  AppHqRoute: typeof AppHqRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppMdRoute: typeof AppMdRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppApplyIdRoute: typeof AppApplyIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidateRoute: AppCandidateRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployerRoute: AppEmployerRouteWithChildren,
  AppHqRoute: AppHqRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppMdRoute: AppMdRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppApplyIdRoute: AppApplyIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MJobsRouteChildren {
  MJobsIdRoute: typeof MJobsIdRoute
}

const MJobsRouteChildren: MJobsRouteChildren = {
  MJobsIdRoute: MJobsIdRoute,
}

const MJobsRouteWithChildren = MJobsRoute._addFileChildren(MJobsRouteChildren)

interface MRouteChildren {
  MApplicationsRoute: typeof MApplicationsRoute
  MCompanyRoute: typeof MCompanyRoute
  MHomeRoute: typeof MHomeRoute
  MJobsRoute: typeof MJobsRouteWithChildren
  MPostRoute: typeof MPostRoute
  MProfileRoute: typeof MProfileRoute
  MSavedRoute: typeof MSavedRoute
  MIndexRoute: typeof MIndexRoute
  MEditJobIdRoute: typeof MEditJobIdRoute
}

const MRouteChildren: MRouteChildren = {
  MApplicationsRoute: MApplicationsRoute,
  MCompanyRoute: MCompanyRoute,
  MHomeRoute: MHomeRoute,
  MJobsRoute: MJobsRouteWithChildren,
  MPostRoute: MPostRoute,
  MProfileRoute: MProfileRoute,
  MSavedRoute: MSavedRoute,
  MIndexRoute: MIndexRoute,
  MEditJobIdRoute: MEditJobIdRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApplicationsRoute: ApplicationsRoute,
  CandidatePreviewRoute: CandidatePreviewRoute,
  ContactRoute: ContactRoute,
  ForEmployersRoute: ForEmployersRoute,
  MRoute: MRouteWithChildren,
  MdPreviewRoute: MdPreviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilesRoute: ProfilesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CandidateCreateAccountRoute: CandidateCreateAccountRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
