/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MRouteImport } from './routes/m'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as MSavedRouteImport } from './routes/m/saved'
import { Route as MProfileRouteImport } from './routes/m/profile'
import { Route as MPostRouteImport } from './routes/m/post'
import { Route as MJobsRouteImport } from './routes/m/jobs'
import { Route as MHomeRouteImport } from './routes/m/home'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMdRouteImport } from './routes/_app/md'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppHqRouteImport } from './routes/_app/hq'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppMdIndexRouteImport } from './routes/_app/md/index'
import { Route as AppEmployerIndexRouteImport } from './routes/_app/employer/index'
import { Route as AppCandidateIndexRouteImport } from './routes/_app/candidate/index'
import { Route as MJobsIdRouteImport } from './routes/m/jobs.$id'
import { Route as AppMdMessagesRouteImport } from './routes/_app/md/messages'
import { Route as AppMdMarketingRouteImport } from './routes/_app/md/marketing'
import { Route as AppMdBankingRouteImport } from './routes/_app/md/banking'
import { Route as AppJobsIdRouteImport } from './routes/_app/jobs.$id'
import { Route as AppHqLeadsRouteImport } from './routes/_app/hq/leads'
import { Route as AppEmployerPostJobRouteImport } from './routes/_app/employer/post-job'
import { Route as AppEmployerJobsRouteImport } from './routes/_app/employer/jobs'
import { Route as AppCandidateSavedRouteImport } from './routes/_app/candidate/saved'
import { Route as AppCandidateApplicationsRouteImport } from './routes/_app/candidate/applications'
import { Route as AppApplyIdRouteImport } from './routes/_app/apply.$id'
import { Route as AppEmployerManageIdRouteImport } from './routes/_app/employer/manage.$id'
import { Route as AppEmployerEditJobIdRouteImport } from './routes/_app/employer/edit-job.$id'
import { Route as AppApplyIdConfirmRouteImport } from './routes/_app/apply.$id.confirm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSavedRoute = MSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MRoute,
} as any)
const MProfileRoute = MProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MRoute,
} as any)
const MPostRoute = MPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => MRoute,
} as any)
const MJobsRoute = MJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => MRoute,
} as any)
const MHomeRoute = MHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMdRoute = AppMdRouteImport.update({
  id: '/md',
  path: '/md',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHqRoute = AppHqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMdIndexRoute = AppMdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMdRoute,
} as any)
const AppEmployerIndexRoute = AppEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateIndexRoute = AppCandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => AppRoute,
} as any)
const MJobsIdRoute = MJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MJobsRoute,
} as any)
const AppMdMessagesRoute = AppMdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdMarketingRoute = AppMdMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppMdRoute,
} as any)
const AppMdBankingRoute = AppMdBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppMdRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppHqLeadsRoute = AppHqLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppHqRoute,
} as any)
const AppEmployerPostJobRoute = AppEmployerPostJobRouteImport.update({
  id: '/employer/post-job',
  path: '/employer/post-job',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerJobsRoute = AppEmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateSavedRoute = AppCandidateSavedRouteImport.update({
  id: '/candidate/saved',
  path: '/candidate/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateApplicationsRoute =
  AppCandidateApplicationsRouteImport.update({
    id: '/candidate/applications',
    path: '/candidate/applications',
    getParentRoute: () => AppRoute,
  } as any)
const AppApplyIdRoute = AppApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerManageIdRoute = AppEmployerManageIdRouteImport.update({
  id: '/employer/manage/$id',
  path: '/employer/manage/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerEditJobIdRoute = AppEmployerEditJobIdRouteImport.update({
  id: '/employer/edit-job/$id',
  path: '/employer/edit-job/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyIdConfirmRoute = AppApplyIdConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AppApplyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/m': typeof MRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hq': typeof AppHqRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/md': typeof AppMdRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/m/': typeof MIndexRoute
  '/apply/$id': typeof AppApplyIdRouteWithChildren
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/saved': typeof AppCandidateSavedRoute
  '/employer/jobs': typeof AppEmployerJobsRoute
  '/employer/post-job': typeof AppEmployerPostJobRoute
  '/hq/leads': typeof AppHqLeadsRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/md/banking': typeof AppMdBankingRoute
  '/md/marketing': typeof AppMdMarketingRoute
  '/md/messages': typeof AppMdMessagesRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/candidate/': typeof AppCandidateIndexRoute
  '/employer/': typeof AppEmployerIndexRoute
  '/md/': typeof AppMdIndexRoute
  '/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hq': typeof AppHqRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies': typeof CompaniesIndexRoute
  '/m': typeof MIndexRoute
  '/apply/$id': typeof AppApplyIdRouteWithChildren
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/saved': typeof AppCandidateSavedRoute
  '/employer/jobs': typeof AppEmployerJobsRoute
  '/employer/post-job': typeof AppEmployerPostJobRoute
  '/hq/leads': typeof AppHqLeadsRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/md/banking': typeof AppMdBankingRoute
  '/md/marketing': typeof AppMdMarketingRoute
  '/md/messages': typeof AppMdMessagesRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/candidate': typeof AppCandidateIndexRoute
  '/employer': typeof AppEmployerIndexRoute
  '/md': typeof AppMdIndexRoute
  '/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/for-employers': typeof ForEmployersRoute
  '/m': typeof MRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hq': typeof AppHqRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/md': typeof AppMdRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/m/home': typeof MHomeRoute
  '/m/jobs': typeof MJobsRouteWithChildren
  '/m/post': typeof MPostRoute
  '/m/profile': typeof MProfileRoute
  '/m/saved': typeof MSavedRoute
  '/companies/': typeof CompaniesIndexRoute
  '/m/': typeof MIndexRoute
  '/_app/apply/$id': typeof AppApplyIdRouteWithChildren
  '/_app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/_app/candidate/saved': typeof AppCandidateSavedRoute
  '/_app/employer/jobs': typeof AppEmployerJobsRoute
  '/_app/employer/post-job': typeof AppEmployerPostJobRoute
  '/_app/hq/leads': typeof AppHqLeadsRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/md/banking': typeof AppMdBankingRoute
  '/_app/md/marketing': typeof AppMdMarketingRoute
  '/_app/md/messages': typeof AppMdMessagesRoute
  '/m/jobs/$id': typeof MJobsIdRoute
  '/_app/candidate/': typeof AppCandidateIndexRoute
  '/_app/employer/': typeof AppEmployerIndexRoute
  '/_app/md/': typeof AppMdIndexRoute
  '/_app/apply/$id/confirm': typeof AppApplyIdConfirmRoute
  '/_app/employer/edit-job/$id': typeof AppEmployerEditJobIdRoute
  '/_app/employer/manage/$id': typeof AppEmployerManageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/for-employers'
    | '/m'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/hq'
    | '/jobs'
    | '/md'
    | '/profile'
    | '/companies/$id'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies/'
    | '/m/'
    | '/apply/$id'
    | '/candidate/applications'
    | '/candidate/saved'
    | '/employer/jobs'
    | '/employer/post-job'
    | '/hq/leads'
    | '/jobs/$id'
    | '/md/banking'
    | '/md/marketing'
    | '/md/messages'
    | '/m/jobs/$id'
    | '/candidate/'
    | '/employer/'
    | '/md/'
    | '/apply/$id/confirm'
    | '/employer/edit-job/$id'
    | '/employer/manage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/for-employers'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/hq'
    | '/jobs'
    | '/profile'
    | '/companies/$id'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies'
    | '/m'
    | '/apply/$id'
    | '/candidate/applications'
    | '/candidate/saved'
    | '/employer/jobs'
    | '/employer/post-job'
    | '/hq/leads'
    | '/jobs/$id'
    | '/md/banking'
    | '/md/marketing'
    | '/md/messages'
    | '/m/jobs/$id'
    | '/candidate'
    | '/employer'
    | '/md'
    | '/apply/$id/confirm'
    | '/employer/edit-job/$id'
    | '/employer/manage/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/for-employers'
    | '/m'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_app/dashboard'
    | '/_app/hq'
    | '/_app/jobs'
    | '/_app/md'
    | '/_app/profile'
    | '/companies/$id'
    | '/m/home'
    | '/m/jobs'
    | '/m/post'
    | '/m/profile'
    | '/m/saved'
    | '/companies/'
    | '/m/'
    | '/_app/apply/$id'
    | '/_app/candidate/applications'
    | '/_app/candidate/saved'
    | '/_app/employer/jobs'
    | '/_app/employer/post-job'
    | '/_app/hq/leads'
    | '/_app/jobs/$id'
    | '/_app/md/banking'
    | '/_app/md/marketing'
    | '/_app/md/messages'
    | '/m/jobs/$id'
    | '/_app/candidate/'
    | '/_app/employer/'
    | '/_app/md/'
    | '/_app/apply/$id/confirm'
    | '/_app/employer/edit-job/$id'
    | '/_app/employer/manage/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForEmployersRoute: typeof ForEmployersRoute
  MRoute: typeof MRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/saved': {
      id: '/m/saved'
      path: '/saved'
      fullPath: '/m/saved'
      preLoaderRoute: typeof MSavedRouteImport
      parentRoute: typeof MRoute
    }
    '/m/profile': {
      id: '/m/profile'
      path: '/profile'
      fullPath: '/m/profile'
      preLoaderRoute: typeof MProfileRouteImport
      parentRoute: typeof MRoute
    }
    '/m/post': {
      id: '/m/post'
      path: '/post'
      fullPath: '/m/post'
      preLoaderRoute: typeof MPostRouteImport
      parentRoute: typeof MRoute
    }
    '/m/jobs': {
      id: '/m/jobs'
      path: '/jobs'
      fullPath: '/m/jobs'
      preLoaderRoute: typeof MJobsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/home': {
      id: '/m/home'
      path: '/home'
      fullPath: '/m/home'
      preLoaderRoute: typeof MHomeRouteImport
      parentRoute: typeof MRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/md': {
      id: '/_app/md'
      path: '/md'
      fullPath: '/md'
      preLoaderRoute: typeof AppMdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hq': {
      id: '/_app/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof AppHqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/md/': {
      id: '/_app/md/'
      path: '/'
      fullPath: '/md/'
      preLoaderRoute: typeof AppMdIndexRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/employer/': {
      id: '/_app/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AppEmployerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/': {
      id: '/_app/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AppCandidateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/jobs/$id': {
      id: '/m/jobs/$id'
      path: '/$id'
      fullPath: '/m/jobs/$id'
      preLoaderRoute: typeof MJobsIdRouteImport
      parentRoute: typeof MJobsRoute
    }
    '/_app/md/messages': {
      id: '/_app/md/messages'
      path: '/messages'
      fullPath: '/md/messages'
      preLoaderRoute: typeof AppMdMessagesRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/marketing': {
      id: '/_app/md/marketing'
      path: '/marketing'
      fullPath: '/md/marketing'
      preLoaderRoute: typeof AppMdMarketingRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/md/banking': {
      id: '/_app/md/banking'
      path: '/banking'
      fullPath: '/md/banking'
      preLoaderRoute: typeof AppMdBankingRouteImport
      parentRoute: typeof AppMdRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/hq/leads': {
      id: '/_app/hq/leads'
      path: '/leads'
      fullPath: '/hq/leads'
      preLoaderRoute: typeof AppHqLeadsRouteImport
      parentRoute: typeof AppHqRoute
    }
    '/_app/employer/post-job': {
      id: '/_app/employer/post-job'
      path: '/employer/post-job'
      fullPath: '/employer/post-job'
      preLoaderRoute: typeof AppEmployerPostJobRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/jobs': {
      id: '/_app/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AppEmployerJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/saved': {
      id: '/_app/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof AppCandidateSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/applications': {
      id: '/_app/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AppCandidateApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply/$id': {
      id: '/_app/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof AppApplyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/manage/$id': {
      id: '/_app/employer/manage/$id'
      path: '/employer/manage/$id'
      fullPath: '/employer/manage/$id'
      preLoaderRoute: typeof AppEmployerManageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/edit-job/$id': {
      id: '/_app/employer/edit-job/$id'
      path: '/employer/edit-job/$id'
      fullPath: '/employer/edit-job/$id'
      preLoaderRoute: typeof AppEmployerEditJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply/$id/confirm': {
      id: '/_app/apply/$id/confirm'
      path: '/confirm'
      fullPath: '/apply/$id/confirm'
      preLoaderRoute: typeof AppApplyIdConfirmRouteImport
      parentRoute: typeof AppApplyIdRoute
    }
  }
}

interface AppHqRouteChildren {
  AppHqLeadsRoute: typeof AppHqLeadsRoute
}

const AppHqRouteChildren: AppHqRouteChildren = {
  AppHqLeadsRoute: AppHqLeadsRoute,
}

const AppHqRouteWithChildren = AppHqRoute._addFileChildren(AppHqRouteChildren)

interface AppJobsRouteChildren {
  AppJobsIdRoute: typeof AppJobsIdRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsIdRoute: AppJobsIdRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppMdRouteChildren {
  AppMdBankingRoute: typeof AppMdBankingRoute
  AppMdMarketingRoute: typeof AppMdMarketingRoute
  AppMdMessagesRoute: typeof AppMdMessagesRoute
  AppMdIndexRoute: typeof AppMdIndexRoute
}

const AppMdRouteChildren: AppMdRouteChildren = {
  AppMdBankingRoute: AppMdBankingRoute,
  AppMdMarketingRoute: AppMdMarketingRoute,
  AppMdMessagesRoute: AppMdMessagesRoute,
  AppMdIndexRoute: AppMdIndexRoute,
}

const AppMdRouteWithChildren = AppMdRoute._addFileChildren(AppMdRouteChildren)

interface AppApplyIdRouteChildren {
  AppApplyIdConfirmRoute: typeof AppApplyIdConfirmRoute
}

const AppApplyIdRouteChildren: AppApplyIdRouteChildren = {
  AppApplyIdConfirmRoute: AppApplyIdConfirmRoute,
}

const AppApplyIdRouteWithChildren = AppApplyIdRoute._addFileChildren(
  AppApplyIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHqRoute: typeof AppHqRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppMdRoute: typeof AppMdRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppApplyIdRoute: typeof AppApplyIdRouteWithChildren
  AppCandidateApplicationsRoute: typeof AppCandidateApplicationsRoute
  AppCandidateSavedRoute: typeof AppCandidateSavedRoute
  AppEmployerJobsRoute: typeof AppEmployerJobsRoute
  AppEmployerPostJobRoute: typeof AppEmployerPostJobRoute
  AppCandidateIndexRoute: typeof AppCandidateIndexRoute
  AppEmployerIndexRoute: typeof AppEmployerIndexRoute
  AppEmployerEditJobIdRoute: typeof AppEmployerEditJobIdRoute
  AppEmployerManageIdRoute: typeof AppEmployerManageIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHqRoute: AppHqRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppMdRoute: AppMdRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppApplyIdRoute: AppApplyIdRouteWithChildren,
  AppCandidateApplicationsRoute: AppCandidateApplicationsRoute,
  AppCandidateSavedRoute: AppCandidateSavedRoute,
  AppEmployerJobsRoute: AppEmployerJobsRoute,
  AppEmployerPostJobRoute: AppEmployerPostJobRoute,
  AppCandidateIndexRoute: AppCandidateIndexRoute,
  AppEmployerIndexRoute: AppEmployerIndexRoute,
  AppEmployerEditJobIdRoute: AppEmployerEditJobIdRoute,
  AppEmployerManageIdRoute: AppEmployerManageIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MJobsRouteChildren {
  MJobsIdRoute: typeof MJobsIdRoute
}

const MJobsRouteChildren: MJobsRouteChildren = {
  MJobsIdRoute: MJobsIdRoute,
}

const MJobsRouteWithChildren = MJobsRoute._addFileChildren(MJobsRouteChildren)

interface MRouteChildren {
  MHomeRoute: typeof MHomeRoute
  MJobsRoute: typeof MJobsRouteWithChildren
  MPostRoute: typeof MPostRoute
  MProfileRoute: typeof MProfileRoute
  MSavedRoute: typeof MSavedRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MHomeRoute: MHomeRoute,
  MJobsRoute: MJobsRouteWithChildren,
  MPostRoute: MPostRoute,
  MProfileRoute: MProfileRoute,
  MSavedRoute: MSavedRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForEmployersRoute: ForEmployersRoute,
  MRoute: MRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
